DROP TABLE IF EXISTS weather_response CASCADE;
DROP TABLE IF EXISTS weather_data CASCADE;
DROP TABLE IF EXISTS probability CASCADE;
DROP TABLE IF EXISTS precipitation CASCADE;
DROP TABLE IF EXISTS hourly_data CASCADE;
DROP TABLE IF EXISTS wind CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;